language: java
jdk:
  - oraclejdk8

addons:
  firefox: "43.0"

before_script:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -c "CREATE USER pivotal WITH PASSWORD '';" -U postgres
  - psql -c 'CREATE DATABASE pivotal OWNER = pivotal;' -U postgres

script:
  - mvn test
  - node_modules/karma/bin/karma start karma.conf.js --single-run
