branches:
  only:
    - master

language: java
jdk:
  - oraclejdk8

addons:
  firefox: "43.0"

install: /bin/true

before_script:
  - ( cd frontend; npm install )
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ./gradlew
