language: java
jdk:
  - oraclejdk8

addons:
  firefox: "43.0"
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -c "CREATE USER pivotal WITH PASSWORD '';" -U postgres
  - psql -c 'CREATE DATABASE test OWNER = pivotal;' -U postgres

script:
  - ./gradlew
