language: java
jdk:
  - oraclejdk8

addons:
  firefox: "43.0"
  postgresql: "9.4"

services:
  - postgresql

install: /bin/true

before_script:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -c 'CREATE DATABASE local_parrit_test;' -U postgres

script:
  - ./gradlew
