language: java
jdk:
  - oraclejdk8

before_script:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - mvn test
  - node_modules/karma/bin/karma start karma.conf.js --single-run
